Fix button for server side rendering
primefaces/primeng pull request #10155
Opened 2021-04-25 10:10 UTC by PaveLiArcH

Relates #9036

###Defect Fixes
Fixes button errors for angular universal (SSR).
Use renderer2 instead of direct DOM manipulations.

Errors before PR:
```
ERROR ReferenceError: document is not defined
    at ButtonDirective.createIconEl (./test-project/dist/test-project/server/main.js:157135:27)
    at ButtonDirective.ngAfterViewInit (./test-project/dist/test-project/server/main.js:157104:18)
    at callHook (./test-project/dist/test-project/server/main.js:122038:22)
    at callHooks (./test-project/dist/test-project/server/main.js:122007:17)
    at executeInitAndCheckHooks (./test-project/dist/test-project/server/main.js:121958:9)
    at refreshView (./test-project/dist/test-project/server/main.js:129002:21)
    at refreshEmbeddedViews (./test-project/dist/test-project/server/main.js:130056:17)
    at refreshView (./test-project/dist/test-project/server/main.js:128955:9)
    at refreshComponent (./test-project/dist/test-project/server/main.js:130102:13)
    at refreshChildComponents (./test-project/dist/test-project/server/main.js:128728:9)
```

2021-12-28 22:59 UTC, s4m0r4m4 commented
@yigitfindikli - this seems like a nice fix for the button to work in SSR, though I have not tried it. Can we get eyes on this PR?

2023-03-24 08:28 UTC, cetincakiroglu commented
Hi,

Angular Universal support is in progress now could you please resolve merge conflicts, so we can review and merge safely?

2023-03-24 09:11 UTC, cetincakiroglu requested changes
need to resolve conflicts

2023-03-28 17:22 UTC, PaveLiArcH commented
@cetincakiroglu, looks like already fixed by #12735

2023-03-28 17:22 UTC, closed without merging