Enhancements and refactor for Angular Universal Support
primefaces/primeng pull request #12820
Opened 2023-03-26 21:52 UTC by cetincakiroglu

2023-03-27 17:27 UTC, volvachev commented
Hi mb add [package](https://github.com/ng-web-apis/common) to use tokens like `WINDOW`.

2023-03-29 00:12 UTC, kyjus25 requested changes
Several files here have a copy-paste change to documentation files that should remain the word "document".

2023-03-29 00:12 UTC, kyjus25 commented on src/app/showcase/doc/dock/menuitemdoc.ts
Revert change

2023-03-29 00:12 UTC, kyjus25 commented on src/app/showcase/doc/editor/propsdoc.ts
Revert change

2023-03-29 00:12 UTC, kyjus25 commented on src/app/showcase/doc/blockui/documentdoc.ts
Revert change

2023-03-29 00:12 UTC, kyjus25 commented on src/app/showcase/doc/breadcrumb/menuitemdoc.ts
Revert change

2023-03-29 00:12 UTC, kyjus25 commented on src/app/showcase/doc/contextmenu/documentdoc.ts
Revert change

2023-03-29 00:12 UTC, kyjus25 commented on src/app/showcase/doc/contextmenu/menuitemdoc.ts
Revert change

2023-03-29 00:12 UTC, kyjus25 commented on src/app/showcase/doc/megamenu/megamenuitemdoc.ts
Revert change

2023-03-29 00:12 UTC, kyjus25 commented on src/app/showcase/doc/menu/menuitemdoc.ts
Revert change

2023-03-29 00:12 UTC, kyjus25 commented on src/app/showcase/doc/menubar/menuitemdoc.ts
Revert change

2023-03-29 00:12 UTC, kyjus25 commented on src/app/showcase/doc/panelmenu/menuitemdoc.ts
Revert change

2023-03-29 00:12 UTC, kyjus25 commented on src/app/showcase/doc/slidemenu/menuitemdoc.ts
Revert change

2023-03-29 00:12 UTC, kyjus25 commented on src/app/showcase/doc/steps/menuitemdoc.ts
Revert change

2023-03-29 00:12 UTC, kyjus25 commented on src/app/showcase/doc/table/exportdoc.ts
Revert changes

2023-03-29 00:12 UTC, kyjus25 commented on src/app/showcase/doc/tabmenu/menuitemdoc.ts
Revert change

2023-03-29 00:12 UTC, kyjus25 commented on src/app/showcase/doc/theming/scalingdoc.ts
Revert change

2023-03-29 00:12 UTC, kyjus25 commented on src/app/showcase/doc/tieredmenu/menuitemdoc.ts
Revert change

2023-03-29 07:57 UTC, cetincakiroglu commented
> 

Thanks for indicating that copy-paste issues. All fixed

2023-03-29 14:39 UTC, merged