Fixed dropdown issue. When mouse out dropdown will be closed! (Issue number #16101)
primefaces/primeng pull request #16104
Opened 2024-07-26 05:54 UTC by harii-tilavat

### Defect Fixes
When submitting a PR, please also <ins>**create an issue**</ins> documenting the error and [manually link to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#manually-linking-a-pull-request-or-branch-to-an-issue-using-the-issue-sidebar) or mention it in the description using #<issue_id>.

### Feature Requests
Due to company policy, we are unable to accept feature request PRs with significant changes as such cases has to be implemented by our team following our own processes.
Smaller scaled feature implementations such as adding a property to a component will be considered for merging.

2024-07-26 08:38 UTC, rosenthalj requested changes
Has this PR #16104 been tested against all the documentation examples?  Wouldn't this change automatically close the menu for mouse out regardless of whether or not autoHide=true?  The default is autoHide=false.

2024-07-26 08:38 UTC, rosenthalj commented on src/app/components/menubar/menubar.ts
>      }
Untested,   but shouldn't the contents of the onItemMouseLeave be changed to this:

```
    onItemMouseLeave() {
        if (this.autoHide) {
             this.activeItemPath = [];
             this.menubarService.mouseLeaves.next(true);
        }
    }
```

2024-09-16 21:08 UTC, docentYT commented
Also fixes #10728

2024-11-18 13:11 UTC, mertsincan commented
Could you please update your PR? Thanks a lot for your contribution!

2024-12-06 23:08 UTC, mertsincan commented
For now, closed! If a new update comes from your side, please reopen this PR. Thanks a lot for your understanding!

2024-12-06 23:08 UTC, closed without merging